# Generated by Django 5.2.6 on 2025-09-19 12:45

import django.db.models.deletion
import papers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_teammember_bio_alter_teammember_position'),
        ('papers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='team_members',
            field=models.ManyToManyField(blank=True, null=True, related_name='publications', to='core.teammember'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='papers.publisher'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=papers.models.publisher_logo_image_path),
        ),
    ]
