# Generated by Django 5.2.6 on 2025-09-19 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0002_publication_team_members_alter_publication_publisher_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='authors',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='title',
            field=models.TextField(),
        ),
    ]
