# Generated by Django 5.2.6 on 2025-09-19 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0003_alter_publication_authors_alter_publication_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicationBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
                ('label', models.CharField(max_length=127)),
                ('link', models.CharField(max_length=127)),
            ],
        ),
        migrations.CreateModel(
            name='PublicationBadgeLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='papers.publicationbadge')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='papers.publication')),
            ],
            options={
                'unique_together': {('publication', 'badge')},
            },
        ),
        migrations.AddField(
            model_name='publication',
            name='badges',
            field=models.ManyToManyField(blank=True, related_name='publications', through='papers.PublicationBadgeLink', to='papers.publicationbadge'),
        ),
    ]
