version: '3.9'

services:
  web:
    container_name: riml-backend
    networks:
      - app-network
    build: .
    ports:
      - "8001:8000"
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    env_file:
      - .env
#    depends_on:
#      - db
    restart: always

#  db:
#    image: docker.arvancloud.ir/postgres:15-alpine
#    volumes:
#      - postgres_data:/var/lib/postgresql/data/
#    env_file:
#      - .env
#    ports:
#      - "5432:5432"
#    restart: unless-stopped

volumes:
#  postgres_data:
  static_volume:
  media_volume:
