# Generated by Django 4.2.8 on 2025-09-30 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
