# Generated by Django 5.2.6 on 2025-09-19 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='scholar_url',
            field=models.URLField(blank=True, max_length=255),
        ),
    ]
