# Generated by Django 5.2.6 on 2025-09-19 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_teammember_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='position',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
