# Generated by Django 5.2.6 on 2025-09-19 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_teammember_bio_alter_teammember_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='order',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
