# Generated by Django 4.2.8 on 2025-09-29 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
