# Generated by Django 4.2.8 on 2025-09-29 19:55

import club.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_alter_researchfield_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchfield',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=club.models.field_image_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])]),
        ),
    ]
